{{-- Strings para visitas/sync.blade.php (IndexedDB + fetch). --}}
<script>
    window.__syncStrings = @json([
        'visitEm' => __('Visita em '),
        'localIdSuffix' => __(', local :id'),
        'localPendingSuffix' => __(', local a sincronizar'),
        'visitEmptyPending' => __('Nenhuma visita pendente de envio.'),
        'visitSavedCount' => __('Você tem :count visitas guardadas no dispositivo.'),
        'deleteVisitFromDeviceTitle' => __('Excluir esta visita do dispositivo'),
        'deleteLocalFromDeviceTitle' => __('Excluir este local do dispositivo'),
        'exclude' => __('Excluir'),
        'errorDelete' => __('Erro ao excluir: :message'),
        'localEmptyPending' => __('Nenhum local pendente de envio.'),
        'localSavedCount' => __('Você tem :count locais guardados no dispositivo.'),
        'localNoAddress' => __('Local sem endereço informado'),
        'localNumberPrefix' => __('Nº '),
        'sending' => __('Enviando…'),
        'errorLocalValidate' => __('Erro ao validar local.'),
        'localNotSent' => __('Local não enviado: :message'),
        'errorSyncLocais' => __('Erro ao sincronizar locais: :message'),
        'nothingToSend' => __('Nada a enviar.'),
        'visitsNeedLocal' => __(':count visitas dependem de local que não foi enviado. Envie o local primeiro e verifique os dados do local.'),
        'syncedOk' => __('Os dados foram sincronizados.'),
        'syncPartialWarning' => __('Alguns itens não puderam ser enviados (verifique os dados).'),
        'syncVisitError' => __('Erro ao sincronizar.'),
        'noVisitSent' => __('Nenhuma visita foi enviada.'),
        'localNotSentShort' => __('Local não enviado: :message'),
        'verifyLocalData' => __('verifique os dados.'),
        'sessionExpiredRetry' => __('Sessão expirada. Recarregue a página e tente novamente.'),
        'serverErrorStatus' => __('Erro no servidor (:status). Tente novamente ou verifique os dados.'),
        'invalidServerResponse' => __('Resposta inválida do servidor.'),
        'errorShort' => __('Erro'),
        'networkFailure' => __('Falha na rede'),
        'failurePrefix' => __('Falha: :message'),
        'connectionOrServer' => __('sem conexão ou servidor indisponível.'),
        'noVisitsToClear' => __('Nenhuma visita guardada para apagar.'),
        'confirmClearVisits' => __('Apagar as :count visitas guardadas no dispositivo? Elas não poderão ser recuperadas.'),
        'clearing' => __('Apagando…'),
        'clearedDevice' => __('Dados apagados do dispositivo.'),
        'clearError' => __('Erro ao apagar. Tente novamente.'),
        'couldNotLoadSavedVisits' => __('Não foi possível carregar as visitas salvas. Verifique se o navegador permite armazenamento local.'),
        'couldNotLoadLocais' => __('Não foi possível carregar os locais.'),
        'errorWithMessage' => __('Erro :code'),
    ]);
</script>
